Added Readme for helm
kubernetes-sigs/scheduler-plugins pull request #383
Opened 2022-06-03 07:48 UTC by chetak123

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it: Readme for Helm chart along with it's parameters

#### Which issue(s) this PR fixes:

Fixes #353 

#### Special notes for your reviewer:
I have completed task 1 as specified in issue but not able to fully understand task 2 - `Update the` [doc](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md#as-a-second-scheduler) `specifying the steps to use helm chart -if any other place other than the above-`
It would be really helpful if you can please specify what needs to be done,
Thanks.

2022-06-03 22:16 UTC, helayoty commented
/assign @helayoty

2022-06-07 18:34 UTC, helayoty commented on manifests/install/charts/as-a-second-scheduler/README.md
> +| `global.extensions.preFilter`           | global extensions preFilter                                                                                                               | `["Coscheduling
The description should be something like:
 ```markdown
 `preFilter` extension config. This is be used if the `preFilter` plugin is enabled.
 ```

Please apply the same for the rest of all extensions. parameters

2022-06-07 18:40 UTC, helayoty requested changes
Thanks for your contribution. Added some comments.

2022-06-07 18:40 UTC, helayoty commented on manifests/install/charts/as-a-second-scheduler/README.md
> +| `scheduler.replicaCount`                | Scheduler replicaCount                                                                                                                    | `1`
```suggestion
| `scheduler.replicaCount`                | scheduler-plugins replicas                                                                                                                | `1`                                                     |
```

2022-06-07 18:40 UTC, helayoty commented on manifests/install/charts/as-a-second-scheduler/README.md
> +| `plugins.enabled`                       | Plugins enabled                                                                                                                           | `["Coscheduling
```suggestion
| `plugins.enabled`                       | All Plugins are enabled by default. Plugins enabled                                                                                                                           | `["Coscheduling","CapacityScheduling","NodeResourceTopologyMatch", "NodeResourcesAllocatable"]` |
```

2022-06-07 18:40 UTC, helayoty commented on manifests/install/charts/as-a-second-scheduler/README.md
> +| `global.queueSort`                      | global queueSort, needs to be globally enabled once                                                                                       | `["Coscheduling
Please remove `global` from all parameters' descriptions. 
```suggestion
| `global.queueSort`                      |  THe default `queueSort` Plugin, needs to be enabled once                                                                                       | `["Coscheduling"]`                                      |
```

2022-06-15 10:00 UTC, denkensk commented
/ok-to-test

2022-06-23 03:40 UTC, chetak123 commented
Hey @helayoty I have made the required changes.

(and I'm very sorry for the delay - due to exams)

2022-06-29 04:37 UTC, seanmalloy commented on manifests/install/charts/as-a-second-scheduler/README.md
> +
````suggestion
Verify that scheduler and plugin-controller pod are running properly.

```bash
$ kubectl get deploy -n scheduler-plugins
NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
scheduler-plugins-controller   1/1     1            1           7s
scheduler-plugins-scheduler    1/1     1            1           7s
```
````

2022-06-29 04:40 UTC, seanmalloy commented
@chetak123 I added one more suggestion to the README.

I believe we just need to change one thing. Currently the `helm install` commands are duplicated in the README you updated and in this document: https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md#as-a-second-scheduler.

Can you remove the `helm install` commands from `doc/install.md` and replace them with a link to the updated README?

2022-06-29 20:02 UTC, helayoty approved these changes
LGTM 🚢

2022-06-29 20:03 UTC, helayoty commented
/assign @huang-wei

2022-06-29 20:17 UTC, seanmalloy commented
/release-note-none

2022-06-30 05:13 UTC, Huang-Wei commented
/lgtm
/approve
/label tide/merge-method-squash

Thanks @chetak123 !

2022-06-30 05:16 UTC, merged