configure bin-packing in helm chart
kubernetes-sigs/scheduler-plugins pull request #537
Opened 2023-03-05 07:48 UTC by Gekko0114

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Added the explanation on how to configure bin-packing in helm chart.

#### Which issue(s) this PR fixes:
Fixes #448 

#### Special notes for your reviewer:
Thank you for reviewing this PR.
Please let me know if I have made any mistakes or if there are any improvements that could be made.
Your comments and feedback are appreciated.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

2023-03-05 08:25 UTC, zwpaper requested changes
one more question, did you test the functionality locally?

2023-03-05 08:25 UTC, zwpaper commented on manifests/install/charts/as-a-second-scheduler/README.md
> +```yaml
please add an empty line between the doc and the code

2023-03-05 08:25 UTC, zwpaper commented on manifests/install/charts/as-a-second-scheduler/README.md
> +If you want to use bin-packing in the helm chart, you need to add code similar to the following in the `pluginConfig` section of `values.yaml`.
```suggestion
If you want to enable [bin-packing](https://kubernetes.io/docs/concepts/scheduling-eviction/resource-bin-packing/#enabling-bin-packing-using-requestedtocapacityratio) in the helm chart, you need to configure it similar to the following in `pluginConfig` section of `values.yaml`.
```

2023-03-05 08:25 UTC, zwpaper commented on manifests/install/charts/as-a-second-scheduler/README.md
> +```yaml
need an empty line

2023-03-05 08:25 UTC, zwpaper commented on manifests/install/charts/as-a-second-scheduler/README.md
> +Then the ConfigMap will be created.
```suggestion
Then the ConfigMap containing `KubeSchedulerConfiguration` will be created:
```

2023-03-05 08:30 UTC, zwpaper commented
/area helm

2023-03-06 02:03 UTC, Huang-Wei commented
@Gekko0114 Apologize that I should have commented in the original issue that it's not planned to support it in scheduler-plugins. (and hence remote the /help label)

The reason is that bin-packing is supported via one of the in-tree plugins, so the problem domain applies to the upstream default-scheduler, instead of any scheduler plugin that adopts it.

/close not-planned

2023-03-06 03:43 UTC, zwpaper commented
closing due to not planned, check https://github.com/kubernetes-sigs/scheduler-plugins/issues/448

/close

2023-03-06 03:43 UTC, closed without merging

2023-03-06 13:29 UTC, Gekko0114 commented
Got it! Thank you for the information